{{- if and .Values.firebase .Values.firebase.credentials }}
# Firebase Service Account Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "connect-backend.labels" . | nindent 4 }}
    component: firebase
type: Opaque
stringData:
  credentials.json: {{ .Values.firebase.credentials }}
{{- else }}
# Placeholder Firebase credentials secret
# This should be populated manually or via CI/CD with actual service account key
apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "connect-backend.labels" . | nindent 4 }}
    component: firebase
type: Opaque
stringData:
  credentials.json: |
    {
      "type": "service_account",
      "project_id": "{{ .Values.gcp.projectId }}",
      "private_key_id": "dummy-key-id-for-testing",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKB\nxQIDAQAB\n-----END PRIVATE KEY-----\n",
      "client_email": "connect-backend-{{ .Values.environment.name }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com",
      "client_id": "000000000000000000000",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/connect-backend-{{ .Values.environment.name }}%40{{ .Values.gcp.projectId }}.iam.gserviceaccount.com"
    }
{{- end }}