# Firebase Service Account Credentials Secret
# Uses Google Secret Manager integration like other secrets
apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "connect-backend.labels" . | nindent 4 }}
    component: firebase
type: Opaque
stringData:
  credentials.json: "${sm://firebase-credentials}"