apiVersion: v1
kind: Service
metadata:
  name: {{ include "connect-backend.serviceName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "connect-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "connect-backend.selectorLabels" . | nindent 4 }}