# Connect Dating Application - Production Environment Configuration
# Production-ready configuration with all security and features enabled

spring:
  config:
    activate:
      on-profile: prod

# Feature Flags - Production Environment (All features enabled)
app:
  features:
    email-verification: true       # REQUIRED: Users must verify email before login
    email-service: true           # Enable email service for user communications
    push-notifications: true      # Enable push notifications for engagement
    premium-features: true        # Enable subscription and premium features
    admin-features: true          # Enable admin functionality
    realtime-messaging: true      # Enable real-time messaging features
    analytics: true               # Enable user analytics and tracking
    file-uploads: true            # Enable photo and file upload functionality
    social-sharing: true          # Enable social sharing features
    safety-features: true         # REQUIRED: Enable all safety and reporting features
  
  # Development Settings - Production security
  dev:
    expose-reset-tokens: false    # NEVER expose reset tokens in production

# Email Configuration - Production Gmail settings
email:
  enabled: true
  provider: smtp
  from-email: thepromeutheusgroup@gmail.com
  from-name: Connect Dating App
  
  # Gmail SMTP Settings
  smtp-host: smtp.gmail.com
  smtp-port: 587
  username: thepromeutheusgroup@gmail.com
  password: ${EMAIL_PASSWORD:lmtr nxvu dvrc oqim}  # Use environment variable in production
  authentication-enabled: true
  start-tls-enabled: true
  ssl-enabled: false
  
  # Email Settings - Production timeouts
  connection-timeout: 30000
  read-timeout: 30000
  max-retries: 3
  debug-enabled: false

# Logging Configuration - Production logging (minimal for performance)
logging:
  level:
    root: WARN
    com.tpg.connect: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: /var/log/connect/application.log

# Firebase Configuration - Production database
# NOTE: In production, use environment variables for sensitive paths
firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH:/secure/firebase-service-account.json}
  database:
    url: ${FIREBASE_DATABASE_URL:https://connect-production.firebaseio.com}
  storage:
    bucket: ${FIREBASE_STORAGE_BUCKET:connect-production.firebasestorage.app}
  project:
    id: ${FIREBASE_PROJECT_ID:connect-production}

# Google Cloud Storage - Production
gcp:
  project:
    id: ${GCP_PROJECT_ID:connect-production}
  storage:
    bucket: ${GCP_STORAGE_BUCKET:connect-production.firebasestorage.app}
    credentials:
      location: ${GCP_CREDENTIALS_PATH:/secure/firebase-service-account.json}

# Production Security Settings
server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 30m
  compression:
    enabled: true
  http2:
    enabled: true

# Production JWT Settings
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsLongEnough123456789ABCDEF}

# Production Database Connection Pool Settings (if using SQL database)
# spring:
#   datasource:
#     hikari:
#       maximum-pool-size: 20
#       minimum-idle: 5
#       idle-timeout: 600000
#       max-lifetime: 1800000