logging:
    level:
        root: INFO

app:
    dev:
        expose-reset-tokens: true

spring:
    config:
        activate:
            on-profile: dev

# Firebase Configuration (DEV)
firebase:
    config:
        path: /Users/willgraham/Desktop/keys/firebase-service-account.json
    database:
        url: https://connect-ea4c2-default-rtdb.firebaseio.com
    storage:
        bucket: connect-ea4c2.firebasestorage.app
    project:
        id: connect-ea4c2

# Google Cloud Storage (DEV)
gcp:
    project:
        id: connect-ea4c2
    storage:
        bucket: connect-ea4c2.firebasestorage.app
        credentials:
            location: /Users/willgraham/Desktop/keys/firebase-service-account.json