# Connect Dating Application - Integration Environment Configuration
# Used for integration testing with external services - requires real email verification

spring:
  config:
    activate:
      on-profile: int
  cloud:
    gcp:
      secretmanager:
        enabled: true
        project-id: connect-ea4c2-int

# JWT Configuration - Integration Environment
jwt:
  secret: ${sm://jwt-secret}

# Feature Flags - Integration Environment (Selective testing)
app:
  features:
    email-verification: true       # Enable for integration testing with real emails
    email-service: true           # Enable email service for integration testing
    push-notifications: true      # Enable push notifications for testing
    premium-features: true        # Enable premium features for full integration tests
    admin-features: true          # Enable admin features for testing
    realtime-messaging: true      # Enable real-time features for testing
    analytics: false              # Disable analytics to reduce noise
    file-uploads: true            # Enable file uploads for testing
    social-sharing: false         # Disable social sharing in integration
    safety-features: true         # Enable safety features for testing
  
  # Development Settings
  dev:
    expose-reset-tokens: true     # Expose tokens for integration testing

# Email Configuration - Real email service but with test settings
email:
  enabled: true
  provider: smtp
  from-email: ${sm://email-from-email}
  from-name: Connect Dating App - Integration
  
  # Gmail SMTP Settings
  smtp-host: smtp.gmail.com
  smtp-port: 587
  username: ${sm://email-username}
  password: ${sm://email-password}
  authentication-enabled: true
  start-tls-enabled: true
  ssl-enabled: false
  
  # Email Settings - More relaxed timeouts for integration
  connection-timeout: 45000
  read-timeout: 45000
  max-retries: 5
  debug-enabled: true

# Logging Configuration - Balanced for integration testing
logging:
  level:
    root: INFO
    com.tpg.connect: DEBUG
    org.springframework.web: INFO

# Firebase Configuration - Integration database
firebase:
  config:
    path: ${sm://firebase-config-path}
  database:
    url: ${sm://firebase-database-url}
  storage:
    bucket: ${sm://firebase-storage-bucket}
  project:
    id: ${sm://firebase-project-id}

# Google Cloud Storage - Integration
gcp:
  project:
    id: ${sm://gcp-project-id}
  storage:
    bucket: ${sm://gcp-storage-bucket}
    credentials:
      location: ${sm://gcp-credentials-path}