apiVersion: v1
kind: Namespace
metadata:
  name: connect-pre
  labels:
    name: connect-pre
    environment: pre-production
    tier: staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connect-backend-pre
  namespace: connect-pre
  annotations:
    iam.gke.io/gcp-service-account: connect-backend@connect-ea4c2.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: connect-pre
  name: connect-backend-pre-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connect-backend-pre-binding
  namespace: connect-pre
subjects:
- kind: ServiceAccount
  name: connect-backend-pre
  namespace: connect-pre
roleRef:
  kind: Role
  name: connect-backend-pre-role
  apiGroup: rbac.authorization.k8s.io