package com.tpg.connect.model.constants;

import java.util.Arrays;
import java.util.List;

public final class PromptConstants {
    
    private PromptConstants() {
        throw new RuntimeException("Class is Utility");
        // Utility class - prevent instantiation
    }
    
    public static final List<String> WRITTEN_PROMPTS = Arrays.asList(
        "How to pronounce my name",
        "A non-negotiable of mine",
        "A random fact I love",
        "All you need to know about me",
        "Best travel story",
        "Biggest risk I've taken",
        "Change my mind about",
        "First impression of me",
        "Guilty pleasure",
        "I bet you can't",
        "I geek out on",
        "I know the best spot in town for",
        "I like for tips about",
        "I recently got very into",
        "I want someone who",
        "My simple pleasures",
        "My biggest date fail",
        "My greatest strength",
        "My hidden talent",
        "My love language",
        "My most controversial opinion",
        "My therapist would say I",
        "The best way to ask me out",
        "The fastest way to my heart",
        "Two truths and a lie",
        "Unusual skills",
        "We'll get along if",
        "What I'm looking for",
        "You should message me if",
        "A life goal of mine",
        "I'm overly competitive about",
        "The way to win me over is",
        "My zombie apocalypse plan",
        "I'm weirdly attracted to",
        "My most irrational fear",
        "If I could live anywhere",
        "My ideal Sunday",
        "I'm convinced that",
        "My childhood crushes",
        "The dorkiest thing about me",
        "I'm looking for someone who",
        "A shower thought I recently had",
        "My real-life superpower",
        "I won't shut up about",
        "Together we could",
        "My greatest fantasy",
        "The key to my heart is",
        "Never have I ever",
        "My most spontaneous moment",
        "I'm a real sucker for",
        "The one thing I'd like to know about you",
        "If loving this is wrong, I don't want to be right",
        "All I ask is that you",
        "Green flag I look for",
        "My most useless skill is",
        "I'm the type of person who",
        "Worst idea I've had",
        "Something I'll never do again",
        "My biggest weakness",
        "My go-to karaoke song",
        "Something that's important to me",
        "I can go on and on about",
        "A boundary of mine",
        "Don't hate me if I"
    );
    
    public static final List<String> PICTURE_PROMPTS = Arrays.asList(
        "My happiest moment",
        "Perfect Sunday",
        "My favorite adventure",
        "This makes me happy",
        "My happy place",
        "Weekend mood",
        "My favorite hobby",
        "This is my passion",
        "My dream vacation spot",
        "Perfect date idea",
        "My comfort zone",
        "Something I'm proud of",
        "This is me in my element",
        "My creative side",
        "Adventure time",
        "Me trying something new",
        "My guilty pleasure",
        "This describes me perfectly",
        "My favorite memory",
        "What I'm passionate about",
        "My ideal night out",
        "This is my vibe",
        "My favorite place",
        "Something that inspires me",
        "My perfect morning",
        "This is what I live for",
        "My biggest accomplishment",
        "This makes me laugh",
        "My favorite season",
        "This is what matters to me"
    );
    
    public static final List<String> POLL_PROMPTS = Arrays.asList(
        "Best first date idea",
        "Perfect Friday night",
        "Ideal vacation",
        "Dream dinner",
        "Best Netflix genre",
        "Perfect weather",
        "Ideal weekend activity",
        "Best coffee order",
        "Favorite season",
        "Best workout",
        "Perfect pet",
        "Ideal breakfast",
        "Best time to text",
        "Perfect road trip",
        "Best superpower",
        "Ideal concert",
        "Perfect pizza topping",
        "Best way to relax",
        "Ideal date night",
        "Best ice cream flavor"
    );
}