# Integration Environment Configuration
# Lightweight setup for integration testing

# Application configuration
app:
  name: connect-backend
  version: latest

# Image configuration - uses integration GCR
image:
  repository: gcr.io/connect-ea4c2-int/connect-backend
  tag: latest
  pullPolicy: Always

# Environment-specific settings
environment:
  name: int
  springProfile: int
  logLevel: DEBUG
  
# Deployment configuration - minimal resources for testing
deployment:
  replicaCount: 1
  strategy:
    type: Recreate  # Use Recreate for single replica deployments
  
# Resources - smaller allocation for integration
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
    
# Ingress configuration
ingress:
  host: int-api.connect-app.com
  staticIpName: connect-backend-int-ip
  sslCertName: connect-backend-int-ssl
  
# Health checks - more lenient timeouts for testing
healthChecks:
  livenessProbe:
    path: /api/health/live
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    path: /api/health/ready
    initialDelaySeconds: 90
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 5
  startupProbe:
    path: /api/health
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 30
    
# GCP configuration - separate project
gcp:
  projectId: connect-ea4c2-int
  region: us-central1
  zone: us-central1-a
  
# Service Account - integration-specific
serviceAccount:
  name: connect-backend-int
  gcpServiceAccount: connect-backend-int@connect-ea4c2-int.iam.gserviceaccount.com
  
# Namespace
namespace:
  name: connect-int
  labels:
    environment: int
    tier: integration
    
# Secret Manager integration
secretManager:
  projectId: connect-ea4c2-int
  
# Firebase configuration - uses Secret Manager integration like JWT secret
# Firebase credentials are stored in Secret Manager as 'firebase-credentials'
  
# Feature flags - enable all for testing
features:
  emailVerification: true
  emailService: true
  pushNotifications: true
  premiumFeatures: true
  adminFeatures: true
  realtimeMessaging: true
  analytics: false  # Disable analytics in integration
  fileUploads: true
  socialSharing: false  # Disable social sharing in integration
  safetyFeatures: true
  
# Development settings
dev:
  exposeResetTokens: true  # Enable for integration testing
  
# Autoscaling - disabled for integration
autoscaling:
  enabled: false
  
# Pod disruption budget - disabled for single replica
podDisruptionBudget:
  enabled: false