name: Test Trigger

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "🎯 Workflow triggered successfully!"
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"